# Generated by Django 5.0.2 on 2024-02-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio_producto', models.FloatField()),
                ('stock_producto', models.IntegerField(default=0)),
                ('fecha_creacion', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
