# Generated by Django 5.0.2 on 2024-03-05 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categorias_alter_productos_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='categoria_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.categorias'),
            preserve_default=False,
        ),
    ]
